In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
arr=np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]]) 

array([[1, 2],
       [3, 4]])

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [8]:
b=np.matrix(l)

In [9]:
b

matrix([[1, 2, 3, 4]])

In [10]:
a=np.array(l)
