## Logistic Regression For Multiclass Classification

In [1]:
# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)


In [14]:

# define the multinomial logistic regression model For multiclass classification
model=LogisticRegression(solver='lbfgs', max_iter=1000)
#  in newer versions of scikit-learn, the 'lbfgs' solver is the default and supports multinomial logistic regression.

In [12]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [15]:
# trianing model
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [16]:
y_pred=model.predict(X_test)

In [17]:
model.predict_proba(X_test)

array([[1.15187735e-01, 5.68537932e-01, 3.16274333e-01],
       [4.80088059e-02, 9.26495838e-01, 2.54953562e-02],
       [7.39114330e-01, 1.57999085e-01, 1.02886585e-01],
       [6.15511329e-03, 3.05145679e-02, 9.63330319e-01],
       [6.62374229e-02, 8.54661607e-01, 7.91009700e-02],
       [1.02416259e-01, 3.08307079e-01, 5.89276662e-01],
       [3.52515627e-01, 2.28557292e-01, 4.18927081e-01],
       [2.91347663e-01, 1.85187829e-01, 5.23464507e-01],
       [5.08165975e-01, 1.95852060e-01, 2.95981965e-01],
       [6.59180423e-01, 2.26067407e-01, 1.14752170e-01],
       [4.22465408e-02, 3.22733975e-01, 6.35019485e-01],
       [4.68663511e-01, 1.25829239e-01, 4.05507250e-01],
       [8.82730292e-01, 2.13939437e-02, 9.58757645e-02],
       [1.08550190e-01, 6.94552878e-01, 1.96896931e-01],
       [6.94121608e-02, 8.59734374e-01, 7.08534651e-02],
       [5.01323127e-01, 2.15105444e-01, 2.83571428e-01],
       [1.11660631e-01, 8.12498879e-01, 7.58404894e-02],
       [6.20236744e-03, 2.67580

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[57 13 16]
 [15 39  6]
 [ 3 12 39]]
0.675
              precision    recall  f1-score   support

           0       0.76      0.66      0.71        86
           1       0.61      0.65      0.63        60
           2       0.64      0.72      0.68        54

    accuracy                           0.68       200
   macro avg       0.67      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200



#### Implement Logistic Regression on the Iris Dataset to classify the species of iris flowers based on their features.


In [19]:
import pandas as pd
import numpy as np

In [21]:
from sklearn.datasets import load_iris

In [22]:
dataset=load_iris()

In [23]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [24]:
x=pd.DataFrame(dataset.data,columns=dataset.feature_names)
y=pd.DataFrame(dataset.target,columns=['target'])

In [26]:
x


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
model=LogisticRegression(solver='lbfgs', max_iter=1000)

In [30]:
model.fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(max_iter=1000)

In [34]:
y_pred=model.predict(x_test)

In [37]:
model.predict_proba(x_test)

array([[3.80345205e-03, 8.27739555e-01, 1.68456993e-01],
       [9.46967197e-01, 5.30326046e-02, 1.98780926e-07],
       [8.85921564e-09, 1.54852864e-03, 9.98451462e-01],
       [6.48510624e-03, 7.92228860e-01, 2.01286034e-01],
       [1.45756939e-03, 7.74128722e-01, 2.24413709e-01],
       [9.55898531e-01, 4.41012933e-02, 1.76047079e-07],
       [7.80130656e-02, 9.07703918e-01, 1.42830160e-02],
       [1.63855505e-04, 1.54555806e-01, 8.45280339e-01],
       [2.22386211e-03, 7.62851266e-01, 2.34924872e-01],
       [2.84383855e-02, 9.45736908e-01, 2.58247068e-02],
       [4.45445532e-04, 2.42557346e-01, 7.56997209e-01],
       [9.68124958e-01, 3.18749636e-02, 7.79521114e-08],
       [9.73004543e-01, 2.69954236e-02, 3.31824509e-08],
       [9.61905843e-01, 3.80940462e-02, 1.10699445e-07],
       [9.79284718e-01, 2.07152172e-02, 6.44560758e-08],
       [4.59447440e-03, 7.12373320e-01, 2.83032206e-01],
       [7.31589685e-06, 2.41373307e-02, 9.75855353e-01],
       [2.73610904e-02, 9.47767

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

